---
- name: Adicionar dependências para repositórios externos
  apt:
    name: [ 'software-properties-common', 'apt-transport-https', 'wget' ]
    state: present

- name: Adicionar chave GPG do Grafana
  apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present

- name: Adicionar repositório estável do Grafana
  apt_repository:
    repo: deb https://apt.grafana.com stable main
    state: present
    update_cache: yes

- name: Instalar pacotes de monitoramento disponíveis (Prometheus/Grafana)
  apt:
    name: [ 'prometheus', 'prometheus-node-exporter', 'grafana' ]
    state: present

- name: Garantir que o Grafana está rodando e habilitado no boot
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: Liberar Portas do Monitoramento no UFW local (Grafana e Prometheus)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: [ '3000', '9090' ]